language: cpp
sudo: false
cache:
  directories:
  - container
env:
  matrix:
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" DEPLOY="1"
  - CMAKE_GENERATOR="Ninja" CMAKE_VERSION="latest"
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="3.0"
  - CMAKE_GENERATOR="Ninja" CMAKE_VERSION="3.0"
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" COVERAGE="--use-cmake-coverage"
  global:
  - secure: MrmcqPCcX4oDoYmr/F/9YZIGEHfBdkQBK8z8Yf6fXHHJ9m9BjDwXbyLEAzjSSR8vSIPnih6OMIC8Knuw8rLgv0gyx/6g2EJfI46r1VBYKLsBFdq7aBsfotFOgmfcjqrEXlEFLS9MhQgvL0Fr5ebLivmGTslWiNzauSN7t90T16HGvsmX36xjshfaOIqFZtDdWxbpo/OplXoaSOWk1HyNeP4uRO+o7yRI2KhmqVCtOq21sWxbpkoWVlf0oD29QE8NYegs08EjhCjncp5wNW916zWbX/T7KapD8qYbYGFuhqAY3NBBOX2LTjR9h8qZXzjUUCyaWbuEnawvDtA1/uiC7IzyD0NXGQvJX5eAdTqRWuHj0z4SUS/FyepdcW8mnnCaX9+w+j0SfwFomClrHqTKBxZjvVBYM5X2PvFODCHN9rurUp5w8yR4bX+RbF6XHLRgQxb3BllEpKMhPtsYt1Y/Dmsuf9MXP7l56Yyt8MQyzOgXzibmjARH9vXukgnTyEFLqCHacHjGrIaGeYFEumOgGEZIbeSDNqaPZs/p4O/GC5/hKDWUNSs4RHWBjs52ws1Tk8/eowRrE8P/rziz5GfUeMphH6zq9rOVITk2yz1361rX+mwf+dqWt+mS0VYRkr4ynbDh//8vqIRXW+cXdSr5EG/iFsoTXrFyKERlToShplw=
  - secure: H02CXyzFVBVk368lWpdCScovzBrpRLvTxoIl7l/D/TctReggYu7Smeae3r/PCR2izwKKstZRefnGHgicQHO9BHVTNG0HINIrfO7Py2U97dN2v2sRYHuQLCyMjJkmzyXGkKmGyrsYHRS8VSV8nI7sugJSyx43tDwpP6jCuxcGS3Lr/E+wJUyt1Zl/LD7bTlvzFkcNkRSzBG5b9+dXFofwMeLc9wWUOSS3SY+baR0YzcOh2GeKXlziAESG0MGZTfA84fMba5KaqS+Hu2K9VuPIouXWL2FxtONzoFr6zHN3FKV7HCioCDrgGUDnn9EqB+Jb2kaNGmxBkCcblqG099lbVnAnJCZlFn04kK49MdCj9dc6BUUm+Ix4YrpINfoHPCktqaga3Ke7R97m3itrE1DvGXP5fJVu3blR9rKijJrOqy0n6qzOWcnkBdCDmw6AcC9upJ6hmWHKx2oAJ7fq5hkTMFjd4hP4AO2rSi4zIozd4V1PgI2BiCNFpTr6381Vx/RrotagWuREzXiWAY29ahBggSVvcHat7Nn+TlGqtq0dlzMUUQMAcUNWYL5JpUDcUCBn5N0a1cM0e9c1Yt+dpfhjssSmSTkhiDXRs6L2cVEzJok6JHx7IlZCucZWG1k6fx+nsh0umNCXSJQenlmejbEcGaniN11ehV0r0R3JkTiOYNQ=
  - secure: tqlWxTX9SC3B9TYrQlrEbgVPTmEt4MpiC70Bw+t6Gfk2RFeWSNuRd4PH18SqfpG1CA4WkrbDqQT768zGLd4l7DYPKwbbrA0Sz4ZexJkQASq4BmkN2oulsD1Oa9gyNN7FCKGmbid6uypRGz5kjf0D28MBNlqvH1REex/5Ehcy0+t2qVUUS6bmmK8gjelNsRptj6s9tQ+WxmyCsPNACzy93SgCLRSYhgtj+Pe+bTjXekh+r+ObqQAbjCPD7lzKLY4Hl/1EIiC99cDZJpXr603ZScRSrfXxznwGStj7juRBDzy7WJ8AQe6nPz0VTsMPrKojnlCrW+HZ3FktpE3NcdRZoyuwwfOkAbT1YHuKvkUjZ4qdf3eqi/CGTqF6QqVw/sQzvyBOiCpld+CXpSw5p3N+U3zZU/vJZYKOEuo7KX56Bp35A0mU7ne3EfGLBe0DIyscUFoYi3TzSxiJAvp1GDfA8l5udMlId0cXwEkC4Kab9tEJ+gGs7NsI2/U9divtko5cPGxtFb8K6xaVowg4aUx+0E62arVhLkTXnmNbT8Qa/qSUmh9CrgN9/Xb2ZIVzoz0tc6mZFc+6jVHiPs2aSiXftvALkj0jZ83addFHF9nrGJsDKKpLMYIwqn7s3H8JABfEwaGVeHqnwB2cobJcjAkxNsjYdiBPFMPNMHRUIxSrvSk=
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python3.4-dev
install:
- eval $(curl -LSs --retry 100 --connect-timeout 3 public-travis-scripts.polysquare.org/bootstrap.py
  | python /dev/stdin -d container -s setup/conan/setup.py -e bash -p /dev/stdout
  --cmake-version ${CMAKE_VERSION})
script:
- polysquare_run check/conan/check.py ${COVERAGE} --cmake-namespace cmake --generator
  "${CMAKE_GENERATOR}"
before_cache:
- polysquare_cleanup
after_success:
- polysquare_run coverage/cmake/coverage.py
before_deploy:
- polysquare_run deploy/conan/before_deploy.py --package=cmake-include-guard
deploy:
  provider: script
  skip_cleanup: true
  script: "./travis-deploy"
  on:
    repo: polysquare/cmake-include-guard
    branch: master
    condition: "${DEPLOY} = 1"
